routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//********************************
//*           frontend           *
//********************************
Route::group(['prefix' => '/'], function() {
    Route::resource('/', 'frontend\HomePageController');
    Route::resource('/blog', 'frontend\BlogController');
    
});

//********************************
//*           backend            *
//********************************

// login
Route::get('/login-admin-golf', 'backend\LoginController@index')->middleware('CheckLogout');;

Route::post('/login-admin-golf', 'backend\LoginController@PostLogin');

Route::get('/logout-admin-golf', 'backend\LoginController@logout');
// end login

Route::group(['prefix' => '/Home-Admin-Shop', 'middleware' => ['CheckLogin']], function() {

    Route::get('/','backend\HomeAdminController@index')->name('dashboard');
    // blog
    Route::prefix('blog-admin')->name('blog-admin.')->group(function () {
        Route::resource('/', 'backend\ArticleController');
        Route::get('/{id}/edit', 'backend\ArticleController@edit')->name('blog-admin.edit');
        Route::post('/{id}/update', 'backend\ArticleController@update')->name('blog-admin.update');
        Route::get('/{id}/destroy', 'backend\ArticleController@destroy')->name('blog-admin.destroy');
    });
    //end route

});

app/Http/Controllers/frontend/BlogController.php
<?php

namespace App\Http\Controllers\frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.blog.blog');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
    }
}

app/Http/Controllers/frontend/HomePageController.php
<?php

namespace App\Http\Controllers\frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomePageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.homepage.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/frontend/master/banner.blade.php
<section class="banner-area">
    <div class="container">
        <div class="row fullscreen align-items-center justify-content-start">

            <div class="col-lg-12">
                <div class="active-banner-slider owl-carousel">
                    <!-- single-slide -->
                    <div class="row single-slide align-items-center d-flex">
                        <div class="col-lg-5 col-md-6">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
                                    {{--  <span class="add-text text-uppercase">Add to Bag</span>  --}}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="frontend/img/banner/banner1.png" alt="banner1">
                            </div>
                        </div>
                        
                    </div>

                    <div class="row single-slide align-items-center d-flex">
                        <div class="col-lg-5 col-md-6">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
                                    {{--  <span class="add-text text-uppercase">Add to Bag</span>  --}}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="frontend/img/banner/banner2.png" alt="banner2">
                            </div>
                        </div>
                        
                    </div>

                    <div class="row single-slide align-items-center d-flex">
                        <div class="col-lg-5 col-md-6">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
                                    {{--  <span class="add-text text-uppercase">Add to Bag</span>  --}}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="frontend/img/banner/banner3.png" alt="banner3">
                            </div>
                        </div>
                        
                    </div>

                    <div class="row single-slide align-items-center d-flex">
                        <div class="col-lg-5 col-md-6">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
                                    {{--  <span class="add-text text-uppercase">Add to Bag</span>  --}}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="frontend/img/banner/banner4.png" alt="banner3">
                            </div>
                        </div>
                        
                    </div>

                    <div class="row single-slide align-items-center d-flex">
                        <div class="col-lg-5 col-md-6">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
                                    //<span class="add-text text-uppercase">Add to Bag</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="frontend/img/banner/banner5.png" alt="banner3">
                            </div>
                        </div>
                        
                    </div>
                    <!-- single-slide -->
                    <div class="row single-slide">
                        <div class="col-lg-5">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href="#"><span class="lnr lnr-cross"></span></a>
                                    {{--  <span class="add-text text-uppercase">Add to Bag</span>  --}}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="frontend\img\banner\banner1.png" alt="">
                            </div>
                        </div>
                    </div>

                    <div class="row single-slide">
                        <div class="col-lg-5">
                            <div class="banner-content">
                                <h1>Nike New <br>Collection!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt ut labore et
                                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                                <div class="add-bag d-flex align-items-center">
                                    <a class="add-btn" href="#"><span class="lnr lnr-cross"></span></a>
                                    {{--  <span class="add-text text-uppercase">Add to Bag</span>  --}}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="banner-img">
                                <img class="img-fluid" src="frontend\img\banner\banner2.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>

resources/views/frontend/master/footer.blade.php
<footer class="footer-area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Us</h6>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
                        ut labore dolore
                        magna aliqua.
                    </p>
                </div>
            </div>
            <div class="col-lg-4  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>Stay update with our latest</p>
                    <div class="" id="mc_embed_signup">

                        <form target="_blank" novalidate="true"
                            action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                            method="get" class="form-inline">

                            <div class="d-flex flex-row">

                                <input class="form-control" name="EMAIL" placeholder="Enter Email"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                    required="" type="email">


                                <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right"
                                        aria-hidden="true"></i></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value=""
                                        type="text">
                                </div>

                                <!-- <div class="col-lg-4 col-md-4">
                                            <button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
                                        </div>  -->
                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">Instragram Feed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="frontend\img\i1.jpg" alt=""></li>
                        <li><img src="frontend\img\i2.jpg" alt=""></li>
                        <li><img src="frontend\img\i3.jpg" alt=""></li>
                        <li><img src="frontend\img\i4.jpg" alt=""></li>
                        <li><img src="frontend\img\i5.jpg" alt=""></li>
                        <li><img src="frontend\img\i6.jpg" alt=""></li>
                        <li><img src="frontend\img\i7.jpg" alt=""></li>
                        <li><img src="frontend\img\i8.jpg" alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Follow Us</h6>
                    <p>Let us be social</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
            <p class="footer-text m-0">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>
                    document.write(new Date().getFullYear());

                </script> All rights reserved | This template is made with <i class="fa fa-heart-o"
                    aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </div>
</footer>

resources/views/frontend/master/header.blade.php
<header class="header_area sticky-header">
    @include('frontend.master.menu')
    <div class="search_input" id="search_input_box">
        <div class="container">
            <form class="d-flex justify-content-between">
                <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                <button type="submit" class="btn"></button>
                <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
            </form>
        </div>
    </div>
</header>

resources/views/frontend/master/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <base href="{{ asset('')}}">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="frontend\img\fav.png">
    <!-- Author Meta -->
    <meta name="author" content="CodePixar">
    <!-- Meta Description -->
    <meta name="description" content="golf">
    <!-- Meta Keyword -->   
    <meta name="keywords" content="golf">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>
    @hasSection ('title')
        @yield('title')
    
    @elseif ('title-blog')
        @yield('title-blog')
        
    @endif    
        
    </title>
    
    <!--CSS 
        ============================================= -->
    <link rel="stylesheet" href="frontend\css\linearicons.css">
    <link rel="stylesheet" href="frontend\css\font-awesome.min.css">
    <link rel="stylesheet" href="frontend\css\themify-icons.css">
    <link rel="stylesheet" href="frontend\css\bootstrap.css">
    <link rel="stylesheet" href="frontend\css\owl.carousel.css">
    <link rel="stylesheet" href="frontend\css\nice-select.css">
    <link rel="stylesheet" href="frontend\css\nouislider.min.css">
    <link rel="stylesheet" href="frontend\css\ion.rangeSlider.css" />
    <link rel="stylesheet" href="frontend\css\ion.rangeSlider.skinFlat.css" />
    <link rel="stylesheet" href="frontend\css\magnific-popup.css">
    <link rel="stylesheet" href="frontend\css\main.css">

    <link href="img/favicon.ico" rel="icon">
    <link href="frontend\lib\slick\slick.css" rel="stylesheet">
    <link href="frontend\lib\slick\slick-theme.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    
    

    
    
</head>

<body>

    <!-- Start Header Area -->
    @include('frontend.master.header')
    <!-- End Header Area -->

    <!-- start banner Area -->
    @hasSection ('title')
        @include('frontend.master.banner')    
    @else
        
    @endif
    
    <!-- End banner Area -->

    @yield('content')

    <!-- start footer Area -->
    @include('frontend.master.footer')
    <!-- End footer Area -->

    <script src="frontend\js\vendor\jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous">
    </script>
    <script src="frontend\js\vendor\bootstrap.min.js"></script>
    <script src="frontend\js\jquery.ajaxchimp.min.js"></script>
    <script src="frontend\js\jquery.nice-select.min.js"></script>
    <script src="frontend\js\jquery.sticky.js"></script>
    <script src="frontend\js\nouislider.min.js"></script>
    <script src="frontend\js\countdown.js"></script>
    <script src="frontend\js\jquery.magnific-popup.min.js"></script>
    <script src="frontend\js\owl.carousel.min.js"></script>
    <!--gmaps Js-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="frontend\js\gmaps.min.js"></script>
    

    <!-- blog -->
    <script src="frontend\lib\easing\easing.min.js"></script>
    <script src="frontend\lib\slick\slick.min.js"></script>
    <script src="frontend\js\main.js"></script>
    
</body>
</html>

resources/views/frontend/master/menu.blade.php
<div class="main_menu">
    <nav class="navbar navbar-expand-lg navbar-light main_box">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand logo_h" href="index.html"><img src="frontend\img\logo.png" alt=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                <ul class="nav navbar-nav menu_nav ml-auto">
                    <li class="nav-item active"><a class="nav-link" href="{{ route('index') }}" >Home</a></li>
                    <li class="nav-item submenu dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false">Shop</a>
                        <ul class="dropdown-menu">
                            <li class="nav-item"><a class="nav-link" href="category.html">Shop Category</a></li>
                            <li class="nav-item"><a class="nav-link" href="single-product.html">Product
                                    Details</a></li>
                            <li class="nav-item"><a class="nav-link" href="checkout.html">Product Checkout</a>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="cart.html">Shopping Cart</a></li>
                            <li class="nav-item"><a class="nav-link" href="confirmation.html">Confirmation</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item submenu dropdown">
                        <a href="{{ route('blog.index') }}"  class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false">News</a>
                        <ul class="dropdown-menu">
                            <li class="nav-item"><a class="nav-link" href="{{ route('blog.index') }}">Blog</a></li>
                            <li class="nav-item"><a class="nav-link" href="single-blog.html">Blog Details</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item submenu dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false">Pages</a>
                        <ul class="dropdown-menu">
                            <li class="nav-item"><a class="nav-link" href="login.html">Login</a></li>
                            <li class="nav-item"><a class="nav-link" href="tracking.html">Tracking</a></li>
                            <li class="nav-item"><a class="nav-link" href="elements.html">Elements</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item"><a href="#" class="cart"><span class="ti-bag"></span></a></li>
                    <li class="nav-item">
                        <button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>